src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToMany(targetEntity: Author::class, inversedBy: 'books')]
    private Collection $authors;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publication_date = null;

    #[ORM\ManyToOne(inversedBy: 'books')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $catchphrase = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $summary = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_url = null;

    #[ORM\OneToMany(mappedBy: 'book', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\OneToMany(mappedBy: 'book', targetEntity: Loan::class)]
    private Collection $loans;

    public function __construct()
    {
        $this->authors = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->loans = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Author>
     */
    public function getAuthors(): Collection
    {
        return $this->authors;
    }

    public function addAuthor(Author $author): static
    {
        if (!$this->authors->contains($author)) {
            $this->authors->add($author);
            $author->addBook($this);
        }

        return $this;
    }

    public function removeAuthor(Author $author): static
    {
        if ($this->authors->removeElement($author)) {
            $author->removeBook($this);
        }

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getCatchphrase(): ?string
    {
        return $this->catchphrase;
    }

    public function setCatchphrase(string $catchphrase): static
    {
        $this->catchphrase = $catchphrase;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): static
    {
        $this->summary = $summary;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(?string $image_url): static
    {
        $this->image_url = $image_url;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setBook($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getBook() === $this) {
                $comment->setBook(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Loan>
     */
    public function getLoans(): Collection
    {
        return $this->loans;
    }

    public function addLoan(Loan $loan): static
    {
        if (!$this->loans->contains($loan)) {
            $this->loans->add($loan);
            $loan->setBook($this);
        }

        return $this;
    }

    public function removeLoan(Loan $loan): static
    {
        if ($this->loans->removeElement($loan)) {
            // set the owning side to null (unless already changed)
            if ($loan->getBook() === $this) {
                $loan->setBook(null);
            }
        }

        return $this;
    }

    public function hasCurrentLoan(){
        $hasLoan = false;
        if(count($this->loans->getValues()) > 0){
            $lastLoan = $this->loans->last();
            $hasLoan = $lastLoan->getStatus() == 1 || $lastLoan->getStatus() == 2;
        }
        

        return $hasLoan;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Author;
use App\Entity\Book;
use App\Entity\Category;
use App\Repository\AuthorRepository;
use App\Repository\CategoryRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'required' => true,
            ])
            ->add('catchphrase', TextareaType::class, [
                'required' => true,
            ])
            ->add('summary', TextareaType::class, [
                'attr' => ['rows' => 7],
                'required' => true
            ])
            ->add('authors', EntityType::class, [
                'class' => Author::class,
                'query_builder' => function(AuthorRepository $authorRepository){
                    return $authorRepository->createQueryBuilder('a')
                              ->orderBy('a.name', 'ASC');
                },
                'choice_label' => 'name',
                'multiple' => true,
                'required' => true
            ])
            ->add('publicationDate', DateType::class, [
                'required' => true
            ])
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'query_builder' => function(CategoryRepository $categoryRepository){
                    return $categoryRepository->createQueryBuilder('c')
                              ->orderBy('c.name', 'ASC');
                },
                'choice_label' => 'name',
                'required' => true
            ])
            ->add('image', FileType::class, [
                'label' => 'Image',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '2048k',
                        'mimeTypes' => [
                            'image/*',
                        ],
                        'mimeTypesMessage' => 'Veuillez téléverser une image valide',
                    ])
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Entity\Comment;
use App\Form\CommentType;
use App\Repository\BookRepository;
use App\Form\SearchBookType;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BookController extends AbstractController
{
    #[Route('/books', name: 'books_home')]
    public function index(
        BookRepository $bookRepository,
        Request $request
    ): Response
    {
        $books = $bookRepository->findAll();

        $form = $this->createForm(SearchBookType::class);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $formData = $form->getData();
            $repoOptions = array();

            if($formData['title']){
                $repoOptions['title'] = array(
                    'type' => 'like',
                    'value' => $formData['title']
                );
            }

            if($formData['category']){
                $repoOptions['category'] = array(
                    'type' => '==',
                    'value' => $formData['category']->getId()
                );
            }

            if($formData['publicationDate']){
                $repoOptions['publication_date'] = array(
                    'type' => 'date',
                    'value' => $formData['publicationDate']
                );
            }

            $books = $bookRepository->searchBy($repoOptions);

            if(count($formData['authors']->getValues())){
                $displayedBooks = array();
                foreach($books as $book){
                    $toInclude = true;
                    foreach($formData['authors']->getValues() as $author){
                        $toInclude = $toInclude && in_array($author, $book->getAuthors()->getValues());
                    }
                    if($toInclude){
                        $displayedBooks[] = $book;
                    }
                }
                $books = $displayedBooks;
            }
        }

        $booksAvailability = array();
        foreach($books as $book){
            $booksAvailability[$book->getId()] = !$book->hasCurrentloan(); 
        }
        
        return $this->render('front/book/books.html.twig', [
            'books' => $books,
            'form' => $form,
            'isAvailable' => $booksAvailability
        ]);
    }

    #[Route('/books/{id}', name: 'books_one')]
    public function one(
        Book $book,
        Request $request,
        EntityManagerInterface $em
    ): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $comment = $form->getData();

            $comment->setUser($this->getUser());
            $comment->setBook($book);
            $comment->setPublicationDate(new DateTime());

            $em->persist($comment);
            $em->flush();
        }

        return $this->render('front/book/book.html.twig', [
            'book' => $book,
            'form' => $form,
            'isAvailable' => !$book->hasCurrentLoan()
        ]);
    }
}

templates/front/book/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails livre {{ book.title }}{% endblock %}

{% if book.imageUrl|length > 0 %}
    {% set image = book.imageUrl %}
{% else %}
    {% set image = asset('/assets/img/image_placeholder.webp') %}
{% endif %}

{% block body %}
    <section id="book-details" class="container pad-v">
        <div class="row">
            <div class="col-xl-6">
                <img src="{{ image }}" width="100%" alt="{{ book.title }}">
            </div>
            <div class="col-xl-6">
                {% if isAvailable %}
                    <span class="badge text-bg-success">
                        Disponible
                    </span>
                {% else %}
                    <span class="badge text-bg-danger">
                        Non Disponible
                    </span>
                {% endif %}
                <h1 class="page-title">{{ book.title }}</h1>
                <p>{{ book.catchphrase }}</p>
                {% if book.comments|length > 0 %}
                    <span class="book-rating">
                        {% set rating = 0 %}
                        {% for comment in book.comments %}
                            {% set rating = rating + comment.rating %}
                        {% endfor %}
                        {% set averageRating = rating / (book.comments|length) %}
                        <i class="bi bi-star-fill">
                            <em>
                                {{ averageRating }}
                            </em>
                        </i>
                    </span>
                {% endif %}
                <div class="associated-authors">
                    Auteurs :
                    {% for author in book.authors %}
                        <a href="{{ path('authors_one', { id: author.id }) }}">{{ author.name }} {{ author.firstname }}</a>
                        {% if author != book.authors|last %}
                        , 
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="book-infos">
            <ul class="nav nav-tabs book-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-target="summary">Résumé</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-target="comments">Commentaires</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-target="add-comment">Ajouter un commentaire</a>
                </li>
            </ul>
            <div class="book-tab-content">
                <div id="summary">
                    <p>
                        {% if book.summary|length > 0 %}
                            {{ book.summary }}
                        {% else %}
                            Aucun résumé à afficher
                        {% endif %}
                    </p>
                </div>
                <div id="comments" style="display: none;">
                    <h2>Commentaires</h2>
                    {% for comment in book.comments %}
                        <div class="card">
                            <div class="card-header">
                                <h3>{{ comment.user.username }}</h3>
                                <i class="bi bi-star-fill"><em>{{ comment.rating }}</em></i>
                            </div>
                            <div class="card-body">
                                <span class="card-title">Publié le {{ comment.publicationDate|date('d-m-Y') }}</span>
                                <p class="card-text">{{ comment.comment }}</p>
                            </div>
                        </div>
                    {% endfor %}

                    {% if book.comments|length < 1 %}
                        <p class="col-xl-3">Aucun commentaire trouvé</p>
                    {% endif %}
                </div>
                <div id="add-comment" style="display:none">
                    <h2>Ajouter un commentaire</h2>
                    {{ form_start(form, { attr: { class: 'row' } }) }}
                        <div class="form-group col-12">
                            {{ form_label(form.rating, 'Note', { attr: { 'class': 'form-label' } }) }}
                            {{ form_widget(form.rating, { attr: { 'class': 'form-control visually-hidden' } }) }}
                            <div id="star-rating">
                                <i class="bi bi-star" data-value="1"></i>
                                <i class="bi bi-star" data-value="2"></i>
                                <i class="bi bi-star" data-value="3"></i>
                                <i class="bi bi-star" data-value="4"></i>
                                <i class="bi bi-star" data-value="5"></i>
                            </div>
                        </div>
                        <div class="form-group col-12">
                            {{ form_label(form.comment, 'Commentaire', { attr: { 'class': 'form-label' } }) }}
                            {{ form_widget(form.comment, { attr: { 'class': 'form-control' } }) }}
                        </div>
                        <button type="submit" class="btn btn-primary">Ajouter le commentaire</button>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/front/book/books.html.twig
{% extends 'base.html.twig' %}

{% block title %}liste des livres{% endblock %}

{% block body %}
    <section id="banner" class="books-banner">
        <h1 class="page-title">Liste des livres</h1>
    </section>

    <section id="search-books-form" class="pad-v df-center">
        {{ form_start(form, { attr: { class: 'row' } }) }}
            <div class="form-group col-12 col-xl-6">
                {{ form_label(form.title, 'Titre', { attr: { 'class': 'form-label' } }) }}
                {{ form_widget(form.title, { attr: { 'class': 'form-control' } }) }}
            </div>
            <div class="form-group col-12 col-xl-6">
                {{ form_label(form.publicationDate, 'Date de publication', { attr: { 'class': 'form-label' } }) }}
                {{ form_widget(form.publicationDate, { attr: { 'class': 'form-control' } }) }}
            </div>
            <div class="form-group col-12 col-xl-6">
                {{ form_label(form.category, 'Catégorie', { attr: { 'class': 'form-label' } }) }}
                {{ form_widget(form.category, { attr: { 'class': 'select2-multiple form-control' } }) }}
            </div>
            <div class="form-group col-12 col-xl-6">
                {{ form_label(form.authors, 'Auteurs', { attr: { 'class': 'form-label' } }) }}
                {{ form_widget(form.authors, { attr: { 'class': 'select2-multiple form-control' } }) }}
            </div>
            <button type="submit" class="btn btn-primary">Valider</button>
        {{ form_end(form) }}
    </section>

    <section id="books" class="container pad-v">
        <div class="row">
            {% for book in books %}
                {% include 'includes/singlebook.html.twig' with {book: book} %}
            {% endfor %}
            
            {% if books|length % 3 >= 1 %}
                {% for i in 0..(books|length % 3) %}
                    <div class="col-xl-3 d-none d-xl-flex"></div>
                {% endfor %}
            {% endif %}

            {% if books|length % 2 == 1 %}
                <div class="col-5 d-flex d-xl-none"></div>
            {% endif %}

            {% if books|length < 1 %}
                <p class="col-xl-3">Aucun livre trouvé</p>
            {% endif %}
        </div>
    </section>
{% endblock %}